### ISSUE TITLE
Introduce auto formatting in android

### ISSUE THREAD

**Issue by anuragshukla06** [microsoft/rural-crowdsourcing-toolkit#134]

**Comment by divyansh-dxn** [comment]
This issue can be close as fixed by https://github.com/microsoft/rural-crowdsourcing-toolkit-client/pull/3

**Comment by divyansh-dxn** [comment]
Closing this issue as https://github.com/microsoft/rural-crowdsourcing-toolkit-client/pull/3 has been merged.
